name: self_host
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bubble: ^1.2.1
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.1.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/.
