// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArEA_w-Pv1CMjEfBVNHtdQungHmCRl0Ig',
    appId: '1:957489845864:web:ff68e8736aa3036d5e0ddd',
    messagingSenderId: '957489845864',
    projectId: 'self-host-devkotes',
    authDomain: 'self-host-devkotes.firebaseapp.com',
    storageBucket: 'self-host-devkotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznQlfT6dMyviYEWcPqpL6u3ZarT6077Y',
    appId: '1:957489845864:android:eb132c0a56459c565e0ddd',
    messagingSenderId: '957489845864',
    projectId: 'self-host-devkotes',
    storageBucket: 'self-host-devkotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Th09wBz35kQZxL3jQ5YnXEVdrOHXFtw',
    appId: '1:957489845864:ios:12d93d23baeb0f055e0ddd',
    messagingSenderId: '957489845864',
    projectId: 'self-host-devkotes',
    storageBucket: 'self-host-devkotes.appspot.com',
    iosClientId: '957489845864-vrjaa2o2rcvvoceog70p66ri84ji4jg4.apps.googleusercontent.com',
    iosBundleId: 'com.devkotes.selfHost',
  );
}
